language: node_js
node_js:
  - "10"
notifications:
  slack:
    secure: F7rH06wkbXS5aOZSDV2AAi+ZRw/vGZTjjU5RJkmhnm/YMwW5RzkVTDw8Go81C4xCWrvBL5qjtLlKn05rl0Cs0tCNPxxB9VnJEDeCKwcrBx4o0JpLm0YMbx1qodnvs1kjtUs79F5tsi+nKF3232s+hkJszocH9GweGLNvA6ptXjZbAlsOSUv/F5EqoRS1igtaN7DNDBrHMhabOytga3BoLzoNpE5mceWuY2PZ/EcrnKgANRa578zoMOX3StYZZ951f5of0ygsmc0aWAjkwaUGLyCsV/ovH4eaLod79YfGHql/9BqDS6H1sq1djzUMRsbz85XqqeJ4DM/wH+CZpT2Kx8dpYP+z65pmpbTwwsl2iLn1lovulAesxUQnB0OVVb/VoZq10uCHwKYcoa0GrWcuvNEgPQ8pVl34VQcKnI7EL/+GyZSMQaJ7f8OBj7BJzFYbRSflMkuSDv3T1v+FntMEGD2mWT7m9opM6a4TrFZe7fk5e73QMfZnYsMdbnTTGK+by50+zWg1GbspKzJsDPIZcE1HzLXayFNrGhO1S7pnbzLvOpmDV8PI0AI0mzZGRy+9ehtNjADwlgB1iQsr9AygyHUujRXM3SHf1wJMHhXeKAsUDjB2L7RSKsXCV6p4ncHX08P+JHtWt4A43jntSwFz1a/b9wPaNKUTAXEAf1e6UWA=
